### ISSUE TITLE
Interface field resolving causes "Concrete type is not handled by instance resolvers on GraphQL union"

### ISSUE THREAD

**Issue by acelot** [davidpdrsn/juniper-from-schema#130]
I have some field that returns an union type:
```graphql
type Query {
  testField: TestFieldResult!
}

union TestFieldResult =
  | Ok
  | SomeProblem
  | AnotherProblem

type Ok {
  dummy: Boolean!
}
```

`SomeProblem` and `AnotherProblem` are implementing one shared interface:
```graphql
type SomeProblem implements ProblemInterface {
  message: String!
}

type AnotherProblem implements ProblemInterface {
  message: String!
}

interface ProblemInterface {
  message: String!
}
```

Now I'm trying to perform the query and I just need to know that there is a problem, I am not interested in a specific one:
```graphql
query {
  testField {
    __typename
    ... on Ok {
      dummy
    }
    ... on ProblemInterface {
      message
    }
  }
}
```

And I getting an error:
```
thread 'actix-rt:worker:2' panicked at 'Concrete type ProblemInterface is not handled by instance resolvers on GraphQL union TestFieldResult'
```

However, if you specify a specific type of problem, then everything works.

**Comment by davidpdrsn** [comment]
Thanks for reporting this! It sounds like a juniper bug to me though. Are you able to build a small project that uses juniper directly, not juniper-from-schema and see if you get the same behavior?

**Comment by davidpdrsn** [comment]
@acelot Have you had a chance to dig more into this?

**Comment by acelot** [comment]
@davidpdrsn Sorry, there was no time to do this. I am doing this right now, I think the result will be in an hour.

**Comment by acelot** [comment]
Yep, I have reproduced an error with juniper only: https://gist.github.com/acelot/0f54704452b9cff373d280ea3ee94d81

My stdout:
```
[2020-10-29T05:45:56Z INFO  actix_server::builder] Starting 8 workers
[2020-10-29T05:45:56Z INFO  actix_server::builder] Starting "actix-web-service-0.0.0.0:3000" service on 0.0.0.0:3000
[2020-10-29T05:45:59Z INFO  actix_web::middleware::logger] 127.0.0.1:51442 "POST / HTTP/1.1" 200 13832 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) AltairGraphQLClient/2.5.1 Chrome/76.0.3809.146 Electron/6.1.12 Safari/537.36" 0.008609
[2020-10-29T05:45:59Z INFO  actix_web::middleware::logger] 127.0.0.1:51442 "POST / HTTP/1.1" 200 13832 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) AltairGraphQLClient/2.5.1 Chrome/76.0.3809.146 Electron/6.1.12 Safari/537.36" 0.020473
thread 'actix-rt:worker:1' panicked at 'Concrete type ProblemInterface is not handled by instance resolvers on GraphQL union TestFieldResult', src/schema.rs:18:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/panicking.rs:483:5
   1: std::panicking::begin_panic_fmt
             at /rustc/31530e5d132ebcc3654baf2e5460599681520af0/library/std/src/panicking.rs:437:5
   2: <juniper_test::schema::TestFieldResult as juniper::types::async_await::GraphQLValueAsync<__S>>::resolve_into_type_async
             at ./src/schema.rs:18:29
   3: juniper::types::async_await::resolve_selection_set_into_async_recursive::{{closure}}
             at /home/pioneer/.cargo/git/checkouts/juniper-aa5e857cd28538c7/f6ec735/juniper/src/types/async_await.rs:326:38
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
   6: juniper::types::async_await::GraphQLValueAsync::resolve_async::{{closure}}
             at /home/pioneer/.cargo/git/checkouts/juniper-aa5e857cd28538c7/f6ec735/juniper/src/types/async_await.rs:104:20
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   8: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
   9: juniper::executor::Executor<CtxT,S>::resolve_async::{{closure}}
             at /home/pioneer/.cargo/git/checkouts/juniper-aa5e857cd28538c7/f6ec735/juniper/src/executor/mod.rs:446:9
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  11: juniper::executor::Executor<CtxT,S>::resolve_with_ctx_async::{{closure}}
             at /home/pioneer/.cargo/git/checkouts/juniper-aa5e857cd28538c7/f6ec735/juniper/src/executor/mod.rs:464:9
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  13: <juniper_test::schema::Query as juniper::types::async_await::GraphQLValueAsync>::resolve_field_async::{{closure}}
             at ./src/schema.rs:9:1
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  15: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  16: juniper::types::async_await::resolve_selection_set_into_async_recursive::{{closure}}::{{closure}}
             at /home/pioneer/.cargo/git/checkouts/juniper-aa5e857cd28538c7/f6ec735/juniper/src/types/async_await.rs:266:31
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  18: <juniper::types::async_await::resolve_selection_set_into_async_recursive::{{closure}}::AsyncValueFuture<A,B,C,D> as core::future::future::Future>::poll
             at /home/pioneer/.cargo/git/checkouts/juniper-aa5e857cd28538c7/f6ec735/juniper/src/types/async_await.rs:190:14
  19: <futures_util::stream::futures_ordered::OrderWrapper<T> as core::future::future::Future>::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/stream/futures_ordered.rs:52:9
  20: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/stream/futures_unordered/mod.rs:542:17
  21: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/stream/stream/mod.rs:1330:9
  22: <futures_util::stream::futures_ordered::FuturesOrdered<Fut> as futures_core::stream::Stream>::poll_next
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/stream/futures_ordered.rs:170:26
  23: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/stream/stream/mod.rs:1330:9
  24: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/stream/stream/next.rs:35:9
  25: juniper::types::async_await::resolve_selection_set_into_async_recursive::{{closure}}
             at /home/pioneer/.cargo/git/checkouts/juniper-aa5e857cd28538c7/f6ec735/juniper/src/types/async_await.rs:363:28
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  27: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  28: juniper::types::async_await::GraphQLValueAsync::resolve_async::{{closure}}
             at /home/pioneer/.cargo/git/checkouts/juniper-aa5e857cd28538c7/f6ec735/juniper/src/types/async_await.rs:104:20
  29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  30: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  31: juniper::executor::Executor<CtxT,S>::resolve_async::{{closure}}
             at /home/pioneer/.cargo/git/checkouts/juniper-aa5e857cd28538c7/f6ec735/juniper/src/executor/mod.rs:446:9
  32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  33: juniper::executor::Executor<CtxT,S>::resolve_into_value_async::{{closure}}
             at /home/pioneer/.cargo/git/checkouts/juniper-aa5e857cd28538c7/f6ec735/juniper/src/executor/mod.rs:490:9
  34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  35: juniper::executor::execute_validated_query_async::{{closure}}
             at /home/pioneer/.cargo/git/checkouts/juniper-aa5e857cd28538c7/f6ec735/juniper/src/executor/mod.rs:941:17
  36: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  37: juniper::execute::{{closure}}
             at /home/pioneer/.cargo/git/checkouts/juniper-aa5e857cd28538c7/f6ec735/juniper/src/lib.rs:296:5
  38: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  39: juniper::http::GraphQLRequest<S>::execute::{{closure}}
             at /home/pioneer/.cargo/git/checkouts/juniper-aa5e857cd28538c7/f6ec735/juniper/src/http/mod.rs:119:19
  40: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  41: juniper::http::GraphQLBatchRequest<S>::execute::{{closure}}
             at /home/pioneer/.cargo/git/checkouts/juniper-aa5e857cd28538c7/f6ec735/juniper/src/http/mod.rs:303:28
  42: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  43: juniper_actix::post_graphql_handler::{{closure}}
             at /home/pioneer/.cargo/git/checkouts/juniper-aa5e857cd28538c7/f6ec735/juniper_actix/src/lib.rs:174:30
  44: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  45: juniper_actix::graphql_handler::{{closure}}
             at /home/pioneer/.cargo/git/checkouts/juniper-aa5e857cd28538c7/f6ec735/juniper_actix/src/lib.rs:102:25
  46: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  47: juniper_test::graphql::{{closure}}
             at ./src/main.rs:14:5
  48: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  49: <actix_web::handler::HandlerServiceResponse<T,R> as core::future::future::Future>::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.1.0/src/handler.rs:138:15
  50: <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.1.0/src/handler.rs:247:20
  51: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/future/map.rs:49:37
  52: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/lib.rs:113:13
  53: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  54: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  55: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/either.rs:64:37
  56: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  57: <actix_web::middleware::logger::LoggerResponse<S,B> as core::future::future::Future>::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.1.0/src/middleware/logger.rs:219:46
  58: <actix_cors::CorsMiddleware<S> as actix_service::Service>::call::{{closure}}
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-cors-0.4.1/src/lib.rs:837:31
  59: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  60: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  61: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.7/src/future/either.rs:64:37
  62: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.0.0/src/h1/dispatcher.rs:392:54
  63: <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.0.0/src/h1/dispatcher.rs:771:38
  64: actix_http::service::State<T,S,B,X,U>::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.0.0/src/service.rs:658:36
  65: <actix_http::service::HttpServiceHandlerResponse<T,S,B,X,U> as core::future::future::Future>::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.0.0/src/service.rs:637:9
  66: <actix_service::and_then::AndThenServiceResponse<A,B> as core::future::future::Future>::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-1.0.6/src/and_then.rs:101:34
  67: <actix_server::service::StreamService<T> as actix_service::Service>::call::{{closure}}
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.4/src/service.rs:85:33
  68: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  69: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/core.rs:173:17
  70: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/loom/std/unsafe_cell.rs:14:9
  71: tokio::runtime::task::core::Core<T,S>::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/core.rs:158:13
  72: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/harness.rs:107:27
  73: core::ops::function::FnOnce::call_once
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  74: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:308:9
  75: std::panicking::try::do_call
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:381:40
  76: __rust_try
  77: std::panicking::try
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:345:19
  78: std::panic::catch_unwind
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:382:14
  79: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/harness.rs:89:19
  80: tokio::runtime::task::raw::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/raw.rs:104:5
  81: tokio::runtime::task::raw::RawTask::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/raw.rs:66:18
  82: tokio::runtime::task::Notified<S>::run
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/mod.rs:169:9
  83: tokio::task::local::LocalSet::tick::{{closure}}
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:408:54
  84: tokio::coop::with_budget::{{closure}}
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127:9
  85: std::thread::local::LocalKey<T>::try_with
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  86: std::thread::local::LocalKey<T>::with
             at /home/pioneer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  87: tokio::coop::with_budget
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120:5
  88: tokio::coop::budget
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96:5
  89: tokio::task::local::LocalSet::tick
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:408:31
  90: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:532:16
  91: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/macros/scoped_tls.rs:63:9
  92: tokio::task::local::LocalSet::with
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:442:9
  93: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:518:9
  94: tokio::task::local::LocalSet::run_until::{{closure}}
             at /home/pioneer/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:392:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 9
```

**Comment by davidpdrsn** [comment]
Alright. Phew. Then I can sleep again. Will you an issue in the juniper repo?

**Comment by acelot** [comment]
https://github.com/graphql-rust/juniper/issues/798

**Comment by acelot** [comment]
This issue is fixed in juniper by https://github.com/graphql-rust/juniper/commit/7597523720b24e9dda3a4e0c94067b852f02465c
This commit was included in the release https://github.com/graphql-rust/juniper/compare/juniper-v0.15.7...master

@davidpdrsn Can you please release a new version of juniper-from-schema?
